imports:
    - { resource: parameters.yml }

services:
    elsensee.postsperpage.listener:
        class: elsensee\postsperpage\event\listener
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @controller.helper
            - @request
            - @template
            - @user
            - %elsensee.postsperpage.acp_position%
            - %elsensee.postsperpage.settings%
        tags:
            - { name: event.listener }
